version: "3.8"

services:
  plex-genre-tagger:
    # To deploy a stack from a Git repository in Portainer, you must use a pre-built image
    # from a Docker repository (like Docker Hub). Make sure you have pushed your image first.
    # See the "Advanced Usage" section in the README for instructions.
    image: ghcr.io/bigjazzz/plex-genre-tagger:latest

    # If you are running this locally (not in Portainer from Git), you can build
    # the image directly from the Dockerfile by commenting out the `image` line above
    # and uncommenting the `build` line below.
    # build: .

    container_name: plex-genre-tagger

    # Environment variables are used to configure the script.
    # Replace the placeholder values with your actual credentials.
    environment:
      - PLEX_URL=http://<YOUR_PLEX_IP_ADDRESS>:32400
      - PLEX_TOKEN=<YOUR_PLEX_TOKEN>
      - TMDB_API_KEY=<YOUR_TMDB_API_KEY>
      # Set the sync mode:
      # 'update'    - for fast, frequent runs to tag new media.
      # 'full-sync' - for slow, periodic runs to refresh all genres.
      - SYNC_MODE=update

    # This is a script that runs and then stops. A restart policy of "no" is appropriate.
    restart: "no"
